apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: products.damian-k8s-initiative.3scale.net
spec:
  group: damian-k8s-initiative.3scale.net
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                description:
                  type: string
                apps_count:
                  type: integer
                backends_count:
                  type: integer
                id:
                  type: integer
                name:
                  type: string
                system_name:
                  type: string
                link:
                  type: string
                links:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      path:
                        type: string
                unread_alerts_count:
                  type: integer
                updated_at:
                  type: string
  names:
    kind: Product
    listKind: ProductList
    plural: products
    shortNames:
      - pdcs
    singular: product
  scope: Namespaced
