kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: products-admin-rb
subjects:
  - kind: ServiceAccount
    name: products-admin
    namespace: damian-k8s-initiative
roleRef:
  kind: Role
  name: products-admin
  apiGroup: ""
